In [83]:
#import necessary library
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [84]:
#read csv
df = pd.read_csv('/Users/prajwalite/Downloads/parkinsons.data')

In [85]:
df.head()

name  MDVP:Fo(Hz)  MDVP:Fhi(Hz)  MDVP:Flo(Hz)  MDVP:Jitter(%)  \
0  phon_R01_S01_1      119.992       157.302        74.997         0.00784   
1  phon_R01_S01_2      122.400       148.650       113.819         0.00968   
2  phon_R01_S01_3      116.682       131.111       111.555         0.01050   
3  phon_R01_S01_4      116.676       137.871       111.366         0.00997   
4  phon_R01_S01_5      116.014       141.781       110.655         0.01284   

   MDVP:Jitter(Abs)  MDVP:RAP  MDVP:PPQ  Jitter:DDP  MDVP:Shimmer  ...  \
0           0.00007   0.00370   0.00554     0.01109       0.04374  ...   
1           0.00008   0.00465   0.00696     0.01394       0.06134  ...   
2           0.00009   0.00544   0.00781     0.01633       0.05233  ...   
3           0.00009   0.00502   0.00698     0.01505       0.05492  ...   
4           0.00011   0.00655   0.00908     0.01966       0.06425  ...   

   Shimmer:DDA      NHR     HNR  status      RPDE       DFA   spread1  \
0      0.06545  0.02211  21.033       1  0.414783  0.815285 -4.813031   
1      0.09403  0.01929  19.085       1  0.458359  0.819521 -4.075192   
2      0.08270  0.01309  20.651       1  0.429895  0.825288 -4.443179   
3      0.08771  0.01353  20.644       1  0.434969  0.819235 -4.117501   
4      0.10470  0.01767  19.649       1  0.417356  0.823484 -3.747787   

    spread2        D2       PPE  
0  0.266482  2.301442  0.284654  
1  0.335590  2.486855  0.368674  
2  0.311173  2.342259  0.332634  
3  0.334147  2.405554  0.368975  
4  0.234513  2.332180  0.410335  

[5 rows x 24 columns]

In [86]:
#check if dataset have null values
df.isnull().sum()

name                0
MDVP:Fo(Hz)         0
MDVP:Fhi(Hz)        0
MDVP:Flo(Hz)        0
MDVP:Jitter(%)      0
MDVP:Jitter(Abs)    0
MDVP:RAP            0
MDVP:PPQ            0
Jitter:DDP          0
MDVP:Shimmer        0
MDVP:Shimmer(dB)    0
Shimmer:APQ3        0
Shimmer:APQ5        0
MDVP:APQ            0
Shimmer:DDA         0
NHR                 0
HNR                 0
status              0
RPDE                0
DFA                 0
spread1             0
spread2             0
D2                  0
PPE                 0
dtype: int64

It is found that dataset has non null values. So there is no need to fill the null values.

In [87]:
df['status'].values

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [88]:
#Split the dataset for trainig and testing
#training data
X= df.loc[:, df.columns != 'status'].values[:,1:] 
#testing data
Y= df.loc[:,'status'].values

In [89]:
X

array([[119.992, 157.302, 74.997, ..., 0.266482, 2.301442, 0.284654],
       [122.4, 148.65, 113.819, ..., 0.33559, 2.486855, 0.368674],
       [116.682, 131.111, 111.555, ..., 0.311173, 2.342259, 0.332634],
       ...,
       [174.688, 240.005, 74.287, ..., 0.158453, 2.679772, 0.131728],
       [198.764, 396.961, 74.904, ..., 0.207454, 2.138608, 0.123306],
       [214.289, 260.277, 77.973, ..., 0.190667, 2.555477, 0.148569]],
      dtype=object)

# Train test Split

In [90]:
xLen = int(0.60*len(X))
yLen = int(0.60*len(Y))
yLen

117

In [91]:
xTrain = X[:xLen]
xTest = X[xLen:]
yTrain = Y[:yLen]
yTest = Y[yLen:]

In [92]:
yTrain

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1])


# Logistic Regression

In [94]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(xTrain , yTrain)

/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [95]:
yPred_LR = model.predict(xTest)

In [96]:
yPred_LR

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [97]:
yTest

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [98]:
from sklearn.metrics import confusion_matrix, accuracy_score
#cm = confusion_matrix(Y_pred  , Y_test)
#print(cm)
accuracy_score(yPred_LR,yTest)

0.7564102564102564

# k-neighbour

In [99]:
from sklearn.neighbors import KNeighborsClassifier
model_KN = KNeighborsClassifier(n_neighbors = 5)
model_KN.fit(xTrain , yTrain)
yPred_KN = model_KN.predict(xTest)

In [100]:
accuracy_score(yPred_KN,yTest)

0.7307692307692307

# SVM 

In [101]:
from sklearn.svm import SVC 
model_svc =SVC(kernel ='sigmoid', random_state = 42)
model_svc.fit(xTrain,yTrain)
yPred_SVM = model_svc.predict(xTest)

In [102]:
accuracy_score(yPred_SVM,yTest)

0.6923076923076923

In [103]:
yTrain.shape

(117,)

In [104]:
#y_train = y_train.reshape((X_train.shape[0],1))

# Out of the classifier used, Logistic Regression gave the highest accuracy. So I will use LR to predic the names of the patients having Parkinsons disease and no Parkinsons disease.

# Get the number of patients predicted for having Parkinsons disease and non-Parkinsons disease

In [118]:
noPD = []
PD = []
j=116  #initalise as 116 because shape of xTrain and yTrain is 117(0 to 116)- 
       #so the next number will be 117 i.e. starting of xTest and yTest
yPred = model.predict(xTest) #Logistic Regression
for i in yPred:
    j += 1
    
    if i == 0:
        noPD.append(df['name'][j])
    else:
        PD.append(df['name'][j])
        
    

In [106]:
xTrain

array([[119.992, 157.302, 74.997, ..., 0.266482, 2.301442, 0.284654],
       [122.4, 148.65, 113.819, ..., 0.33559, 2.486855, 0.368674],
       [116.682, 131.111, 111.555, ..., 0.311173, 2.342259, 0.332634],
       ...,
       [206.327, 226.355, 92.02, ..., 0.181701, 2.938114, 0.115515],
       [151.872, 492.892, 69.085, ..., 0.261549, 2.702355, 0.274407],
       [158.219, 442.557, 71.948, ..., 0.27328, 2.640798, 0.170106]],
      dtype=object)

# List of patients predicted for not having Parkinsons disease

In [145]:
noPD_Score = [0]*len(noPD)
final_noPD = pd.DataFrame(noPD , columns = ['name'])
final_noPD['Predicted output'] = noPD_Score
final_noPD

name  Predicted output
0  phon_R01_S42_1                 0
1  phon_R01_S42_2                 0
2  phon_R01_S42_3                 0
3  phon_R01_S42_5                 0
4  phon_R01_S42_6                 0

# List of patients predicted for having Parkinsons disease

In [152]:
PD_Score = [1]*len(PD)
finalPD = pd.DataFrame(PD , columns = ['name'])
finalPD['Predicted output'] = PD_Score
finalPD

name  Predicted output
0   phon_R01_S27_3                 1
1   phon_R01_S27_4                 1
2   phon_R01_S27_5                 1
3   phon_R01_S27_6                 1
4   phon_R01_S27_7                 1
..             ...               ...
68  phon_R01_S50_2                 1
69  phon_R01_S50_3                 1
70  phon_R01_S50_4                 1
71  phon_R01_S50_5                 1
72  phon_R01_S50_6                 1

[73 rows x 2 columns]

# Combined list of patients for having and not having Parkinsons disease.

In [162]:
final_dataset = pd.concat([finalPD , final_noPD])
final_dataset = final_dataset.reset_index()
final_dataset

index            name  Predicted output
0       0  phon_R01_S27_3                 1
1       1  phon_R01_S27_4                 1
2       2  phon_R01_S27_5                 1
3       3  phon_R01_S27_6                 1
4       4  phon_R01_S27_7                 1
..    ...             ...               ...
73      0  phon_R01_S42_1                 0
74      1  phon_R01_S42_2                 0
75      2  phon_R01_S42_3                 0
76      3  phon_R01_S42_5                 0
77      4  phon_R01_S42_6                 0

[78 rows x 3 columns]

# Conclusion: The Project is successfully completed. The list of all the people predicted for having and not having Parkinson's disease is listed.